application: blogger-infinite-scrolling
version: 1
runtime: go
api_version: go1

# re-direct to index.html if no path is give
- url: /
  static_files: index.html
  upload: index.html

# access the static resources in the root director

- url: /(.*)
  static_files: \1
  upload: (.*)